config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'sales#index'

  resources :dashboards
  resources :customers
  resources :tables
  resources :categories do
    resources :dishes
  end
  resources :dishes
  resources :sales do
    resources :payments
    resources :line_items
  end

  resource :report do
    member do
      get :order
      get :waiter
      get :dish
      get :pdfdish
      get :pdfwaiter
      get :pdforder
    end
  end


end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  before_action :set_table, only: [:show, :edit, :update, :destroy]

  # GET /tables
  # GET /tables.json
  def index
    @tables = Table.paginate(per_page: params[:per_page] || Table.per_page || 10, page: params[:page] || 1)

  end

  # GET /tables/1
  # GET /tables/1.json
  def show
  end

  # GET /tables/new
  def new
    @table = Table.new
  end

  # GET /tables/1/edit
  def edit
  end

  # POST /tables
  # POST /tables.json
  def create
    @table = Table.new(table_params)

    respond_to do |format|
      if @table.save
        format.html { redirect_to @table, notice: 'Table was successfully created.' }
        format.json { render :show, status: :created, location: @table }
      else
        format.html { render :new }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tables/1
  # PATCH/PUT /tables/1.json
  def update
    respond_to do |format|
      if @table.update(table_params)
        format.html { redirect_to @table, notice: 'Table was successfully updated.' }
        format.json { render :show, status: :ok, location: @table }
      else
        format.html { render :edit }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tables/1
  # DELETE /tables/1.json
  def destroy
    @table.destroy
    respond_to do |format|
      format.html { redirect_to tables_url, notice: 'Table was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_table
      @table = Table.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def table_params
      params.require(:table).permit(:name, :capacity, :description)
    end
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/tables/_form.html.haml
.row
  .col-md-6
    = form_for @table do |f|
      - if @table.errors.any?
        #error_explanation
          %h5= "#{pluralize(@table.errors.count, "error")} prohibited this table from being saved:"
          %ul
            - @table.errors.full_messages.each do |msg|
              %li= msg

      .form-group
        = f.label :name
        = f.text_field :name, class: 'form-control'
      .form-group
        = f.label :capacity
        = f.text_field :capacity, class: 'form-control'
      .form-group
        = f.label :description
        = f.text_field :description, class: 'form-control'
      .form-group
        = f.submit 'Save', class: 'btn btn-primary'

app/views/tables/edit.html.haml
%h4.heading Editing table

= render 'form'

= link_to 'Show', @table
\|
= link_to 'Back', tables_path

app/views/tables/index.html.haml
.row
  .col-md-6
    %h4.heading Listing Tables
  .col-md-6
    = link_to 'New Table', new_table_path, class:'pull-right btn btn-primary'

.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Name
        %th Capacity
        %th Description
        %th
        %th
        %th

    %tbody
      - @tables.each do |table|
        %tr
          %td= table.name
          %td= table.capacity
          %td= table.description
          %td= link_to 'Show', table
          %td= link_to 'Edit', edit_table_path(table)
          %td= link_to 'Destroy', table, :method => :delete, :data => { :confirm => 'Are you sure?' }

.clearfix
  = will_paginate @tables, renderer: BootstrapPagination::Rails

app/views/tables/new.html.haml
%h4.heading New table

= render 'form'

= link_to 'Back', tables_path

app/views/tables/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @table.name
%p
  %b Capacity:
  = @table.capacity
%p
  %b Description:
  = @table.description

= link_to 'Edit', edit_table_path(@table)
\|
= link_to 'Back', tables_path