config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'sales#index'

  resources :dashboards
  resources :customers
  resources :tables
  resources :categories do
    resources :dishes
  end
  resources :dishes
  resources :sales do
    resources :payments
    resources :line_items
  end

  resource :report do
    member do
      get :order
      get :waiter
      get :dish
      get :pdfdish
      get :pdfwaiter
      get :pdforder
    end
  end


end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  def order
    @q = Sale.report_data.ransack(params[:q])
    @sales = @q.result.page(params[:page])
    @params = params
  end

  def pdforder
    @sales =Sale.report_data

    html = render_to_string(action: 'pdforder', layout: false)
    pdf = PDFKit.new(html)
    send_data(pdf.to_pdf, :type => 'application/pdf', :disposition => "filename=sales.pdf")

  end


  def waiter
    @q = Waiter.get_report_data.ransack(params[:q])
    @waiters = @q.result.page(params[:page])
    @params = params
  end

  def pdfwaiter

    @waiters =Waiter.get_report_data

    html = render_to_string(action: 'pdfwaiters', layout: false)
    pdf = PDFKit.new(html)
    send_data(pdf.to_pdf, :type => 'application/pdf', :disposition => "filename=waiters.pdf")
  end



  def dish
    @q = LineItem.select("line_items.dish_id, sum(line_items.total_price) as total_sale, sum(quantity) as total_quantity").joins(:dish).group('line_items.dish_id').ransack(params[:q])

    @line_items = @q.result.page(params[:page])
    @params = params

  end

  def pdfdish

    @line_items = LineItem.select("line_items.dish_id, sum(line_items.total_price) as total_sale, sum(quantity) as total_quantity").joins(:dish).group('line_items.dish_id')

    html = render_to_string(action: 'pdish', layout: false)
    pdf = PDFKit.new(html)
    send_data(pdf.to_pdf, :type => 'application/pdf', :disposition => "filename=dish.pdf")
  end
end

app/views/reports/dish.html.haml
%h3 Total sale (Dish wise)

.table-responsive
  %table.table.table-striped.table-hover
    %thead
      %tr
        %th Name
        %th Description
        %th Category
        %th.text-right Total Quantity
        %th.text-right Total Sale

    %tbody
      - @line_items.each do |item|
        %tr
          %td= item.dish.name
          %td= item.dish.description
          %td= item.dish.category.name if item.dish.category
          %td.text-right
            %b.text-danger #{item.total_quantity}
          %td.text-right
            %b.text-danger #{format('%.2f' % item.total_sale)}

%p#pdf_link= link_to "Download Report (PDF)", pdfdish_report_path(), target: '_blank', class:'btn btn-success'

.clearfix
  = will_paginate @line_items, renderer: BootstrapPagination::Rails

app/views/reports/order.html.haml
%h3 Sales Total (Date wise)


.table-responsive
  %table.table.table-striped.table-hover
    %thead
      %tr
        %th Date
        %th.text-right Total Orders
        %th.text-right Total Discount
        %th.text-right Total Tax
        %th.text-right Total Sale

    %tbody
      - @sales.each do |sale|
        %tr
          %td= sale.sale_date
          %td.text-right
            %b.text-danger #{sale.total_orders}
          %td.text-right
            %b.text-danger #{sale.total_discount}
          %td.text-right
            %b.text-danger #{sale.total_tax}
          %td.text-right
            %b.text-danger #{format('%.2f' % sale.total_sale_amount)}

%p#pdf_link= link_to "Download Report (PDF)", pdforder_report_path(), target: '_blank', class:'btn btn-success'

.clearfix
  = will_paginate @sales, renderer: BootstrapPagination::Rails

app/views/reports/pdforder.html.haml
%h3 Total sale (Waiter wise)


%table{width:"100%", style:"border: 1px solid;"}
  %thead
    %tr
      %th Date
      %th{align:"right"} Total Orders
      %th{align:"right"} Total discount
      %th{align:"right"} Total Tax
      %th{align:"right"} Total Sales Amount

  %tbody
    - @sales.each do |sale|
      %tr
        %td{style:"border-top: 1px solid;"}= sale.sale_date
        %td{align:"right", style:"border-top: 1px solid;"}
          %b #{sale.total_orders}
        %td{align:"right", style:"border-top: 1px solid;"}
          %b #{sale.total_discount}
        %td{align:"right", style:"border-top: 1px solid;"}
          %b #{sale.total_tax}
        %td{align:"right", style:"border-top: 1px solid;"}
          %b #{format('%.2f' % sale.total_sale_amount)}

app/views/reports/pdfwaiters.html.haml
%h3 Total sale (Waiter wise)


%table{width:"100%", style:"border: 1px solid;"}
  %thead
    %tr
      %th Waiter Name
      %th{align:"right"} Total Orders
      %th{align:"right"} Total Customers
      %th{align:"right"} Total Sale

  %tbody
    - @waiters.each do |waiter|
      %tr
        %td{style:"border-top: 1px solid;"}= waiter.name
        %td{align:"right", style:"border-top: 1px solid;"}
          %b #{waiter.total_orders}
        %td{align:"right", style:"border-top: 1px solid;"}
          %b #{waiter.total_customers}
        %td{align:"right", style:"border-top: 1px solid;"}
          %b #{format('%.2f' % waiter.total_sale_amount)}

app/views/reports/pdish.html.haml
%h3 Total sale (Dish wise)


%table{width:"100%", style:"border: 1px solid;"}
  %thead
    %tr
      %th Name
      %th Description
      %th Category
      %th{align:"right"} Total quantity
      %th{align:"right"} Total Sale

  %tbody
    - @line_items.each do |item|
      %tr
        %td{style:"border-top: 1px solid;"}= item.dish.name
        %td{style:"border-top: 1px solid;"}= item.dish.description
        %td{style:"border-top: 1px solid;"}= item.dish.category.name if item.dish.category
        %td{align:"right", style:"border-top: 1px solid;"}
          %b #{item.total_quantity}
        %td{align:"right", style:"border-top: 1px solid;"}
          %b #{format('%.2f' % item.total_sale)}

app/views/reports/waiter.html.haml
%h3 Total sale (Waiter wise)


.table-responsive
  %table.table.table-striped.table-hover
    %thead
      %tr
        %th Name
        %th.text-right Total Orders
        %th.text-right Total Customers
        %th.text-right Total Sale

    %tbody
      - @waiters.each do |waiter|
        %tr
          %td= waiter.name
          %td.text-right
            %b.text-danger #{waiter.total_orders}
          %td.text-right
            %b.text-danger #{waiter.total_customers}
          %td.text-right
            %b.text-danger #{format('%.2f' % waiter.total_sale_amount)}

%p#pdf_link= link_to "Download Report (PDF)", pdfwaiter_report_path(), target: '_blank', class:'btn btn-success'

.clearfix
  = will_paginate @waiters, renderer: BootstrapPagination::Rails